### PR TITLE
RestAPI started for opencog

### PR DESCRIPTION
**Pull request by vytasrgl**
Not sure why but it seems when using config file and cog terminal i get segfault.
This however seems to be working.

### CODE REVIEW

**Comment by linas** [comment]
What segfaults?  Opencog should never-ever segfault, no matter what you do wrong; if it is, that is a separate bug report.

Opencog has a bad habit of polluting the file system with these log files. Which are useless, except that if they do segfault, its supposed to write a stack trace into the logfile, so you can catch that.

**Comment by linas** [comment]
Oh, unless you mean "running python inside of opencog itself".  Yeah, that mostly works, but can be kind-of flakey sometimes.  We don't have anyone who cares enough about python to fix the open bugs.  which are here: https://github.com/opencog/atomspace/labels/python  and here: https://github.com/opencog/opencog/issues?q=is%3Aopen+is%3Aissue+label%3Apython -- pleeease open a bug report in "atomspace" and just say "import rest and start restapi crashes in opencog" or something like that -- provide the code snippet.

**Comment by linas** [comment]
The theory is that maybe if we have enough pending python bugs, maybe we can get someone to fix them. :-/

**Comment by linas** [comment]
p.s. if you see bugs or weird unexpected behavior on the current (or future) behavior trees, please open bug reports for each one.  I will try to get to each one in a prompt fashion.

**Comment by vytasrgl** [comment]
Alright will fill bug reports for future.
However this one is same as:
https://github.com/opencog/opencog/issues/1598

**Pull request merged**
