### PR TITLE
Requested interaction behavior

### PR DESCRIPTION
**Pull request by vytasrgl**
Behavior required to control face being interacted with.
Currently implemented in chat section of WebUI.

### CODE REVIEW

**Comment by linas** [comment]
I'm merging now, but will review more carefully tomorrow.  Understanding and merging from Man Hin's change-set is on my to-do list.

**Comment by vytasrgl** [comment]
I think Man Hin's changes can be put on hold as they were for specific purpose only.
Curently the @demaris chat changes should be checked as they don't allow existing chatbot to have emotions yet.

**Comment by demaris** [comment]
Are you saying the emotion changes (both voice and showing EMO and other
gestures) are not working?
I thought they were working yesterday after pulling all changes,  but since
there is still some random drift maybe it's misleading.   I'll have a look.

The sentiment detection is pretty weak so mostly you're going to get
neutral / positive emotions.   Also during conversation
I choose from an alternate set of emotions, weights and persistance to
avoid the situation that you get a strong expression of
emotional change that is uncorrelated with conversation sentiment.  I think
this tends to dampen how much the emotional
changes are obvious and may need to be tuned a bit.   However, the right
solution may be to do less randomized emotion
blending during conversation,  especially if we have better sentiment
detection or "authentic" motivation / emotion.

**Comment by linas** [comment]
OK. BTW, this looks real nice; how long did it take you to do this?  

I just now made some small changes, mostly moving stuff around in the file.

**Comment by linas** [comment]
David, in case you see this: this is the opencog behavior tree, not the owyl behavior tree, and although I ported things over, it is possible that I inserted bugs.  In fact, I think I see one now... the chat stuff is never reached, because the face-expression stuff always takes precedence; I can fix that now.

**Comment by demaris** [comment]
Ah Ok,  I thought Vytas said it wasn't working in owyl (and given all the
flux I wouldn't be surprised, but some changes I made did make it more
subtle - I hoped in a good way.)   I didn't realize there had been any
attempt to integrate,  didn't look at Vytas's git integration yet.

**Comment by vytasrgl** [comment]
Took me almost a day. Checked your minor changes and seems there are still long way to fully understand syntax. Will try to add remaining parts of current owyl meanwhile.

**Comment by linas** [comment]
Cool. The syntax is .. weird and central to it is the concept of the "pattern matcher":  http://wiki.opencog.org/w/Pattern_matcher  The pattern matcher kind-of behaves like ProLog, if you've ever studied prolog.

Documentation for the atom type is here:  http://wiki.opencog.org/wikihome/index.php/Category:Atom_Types 

I have not stopped working on this; I just keep getting interrupted.   I plan to review old and recent changes to owyl, make sure things match, etc.  Also, I plan to make multiple high-level changes.  The most interesting one, this week, is to give her self-awareness, so that, if you ask her, by chat "did you just smile?" she could say "yes" or "no".

**Pull request merged**
