### PR TITLE
correct contexts of psi-rules

### PR DESCRIPTION
**Pull request by amebel**
To be consistent with btree.scm, this is required. Haven't tested though.

### CODE REVIEW

**Comment by linas** [comment]
I am merging because this is clearly an improvement over the previous situation.  (As everyone knows, AndLink is not ordered, so the order in which the terms of an AndLink are evaluated is unpredictable. Thus, using a SequntialAnd does allow the first clause to block the execution of the second clause, if it evaluates to false). 

However, I would think that the correct place to evaluate the `Skip interaction` predicate would be as a part of the demand, not the action.  So if `skip interaction` is true, these rules would never even trigger.

So although this makes things better, its not quite really the right fix.

**Comment by linas** [comment]
p.s. you should be using `btree-psi.scm` not `btree.scm`

**Comment by amebel** [comment]
hrtool from HEAD have options for switching between both btree.scm and btree-psi.scm. I primarily been  working with btree-psi.scm. I observerd the difference while trying to get a better feel of the code.

On the `skip interaction` comment, deciding which predicates to make demand and which part of context, is going to be something we have to figure out as we go. When it comes to modeling sophia, (possibly us too) we have psi-theory + CPM to drive the experimentation on what demands to have,  but what to use for a forklift? :smile:

**Comment by linas** [comment]
well, Vytas added `skip-interaction` basically to just turn off behaviors entirely (from the webui) so that she could play some canned animation.  So `skip-interaction` is really a global off button.  So, for this thing, the real right answer is to move the global off-button to somewhere else.

**Comment by amebel** [comment]
Got it

**Comment by amebel** [comment]
In the coming week, the rules could be tagged to be controlled similar to what was done for chatbot-psi rules in https://github.com/opencog/opencog/pull/2273. That way by making the weight of the psi-rules to be zero similar effect can be achieved. 

Ben has asked me to add the control mechanism on demands as well, that way rules associated with a particular demand can be turnned off, by making the weight of a demand to equal zero. Either means could be used.

**Comment by linas** [comment]
The weight=zero solution sounds much better to me, as a general mechanism.  I don't like the `SequentialAnd is-blah-blah-true?` approach, because it is not scalable. It will work fine for half-a-dozen rules or a bit more, but for thousands of rules (e.g. chat) its impractical to run `is-chat-enabled?` thousands of times per millisecond just to discover that chat has been turned off.

Any mechanism that turns off entire blocks of rules, in some low-cost way, is better.

**Pull request merged**
