### PR TITLE
improvements and review comment fixes

### PR DESCRIPTION
**Pull request by yantrabuddhi**
needs a little more work, i.e. applying ros tf to generated face coordinates before being sent to blender msg api

### CODE REVIEW

**Comment by yantrabuddhi** [comment]
I will make this pull rtequest once I apply and test tf stuff

**Comment by linas** [comment]
OK, thanks. After skimming this, it actually looks nice, and I would have happily merged as is.   But, of course, yes, testing is .. well, crucial.

**Comment by linas** [comment]
How about this: I will re-open, so that we con't forget about this, and agree to not merge until you feel it really is ready?

**Comment by yantrabuddhi** [comment]
Hi Linas,
 I made and tested the changes on Han. Its working okay now. Please review now for merge

**Comment by linas** [comment]
thanks!

**Pull request merged**
