### PR TITLE
Also check ints for openpsi opencog_control

### PR DESCRIPTION
**Pull request by leungmanhin**

### CODE REVIEW

**Comment by amebel** [comment]
what is data.ints?

**Comment by leungmanhin** [comment]
That's integers

**Comment by amebel** [comment]
:-) I mean what do it represent. data.doubles is meant for strength of stv.

**Comment by leungmanhin** [comment]
data.ints is also representing the strength of stv. We were testing the sliders from the webui that day, and when we turned it to either 0 or 1, the data type changed from double to int, and it caused a problem updating the stv of the corresponding psi-rule as this function got doubles only

**Comment by linas** [comment]
so -- this sounds like the wrong fix, then = the webui needs to be fixed so that it always sends floats, even when the endpoints 0, 1 are reached.  This is for maybe @vytasrgl and/or @grebsle ? who does the webui?

**Comment by vytasrgl** [comment]
Actually parameters should be parsed by names and typecasted where
possible.  This is consist with RQT implementation.  However webui also
should make best effort to send correct type.

so -- this sounds like the wrong fix, then = the webui needs to be fixed so
that it always sends floats, even when the endpoints 0, 1 are reached. This
is for maybe @vytasrgl https://github.com/vytasrgl and/or @grebsle
https://github.com/grebsle ? who does the webui?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
https://github.com/opencog/ros-behavior-scripting/pull/71#issuecomment-233384402,
or mute the thread

**Pull request merged**
