### PR TITLE
openpsi dynamics update

### PR DESCRIPTION
**Pull request by eddiemonroe**

### CODE REVIEW

**Comment by linas** [comment]
Eddie, I merged this, but this is now completely the wrong place for this code to live: it really needs to be moved to opencog.  Almost everything was moved to opencog some 3-4 months ago, and the only thing left here are the ROS shims to motors and sensors (sound, cameras).  I did not move the openpsi bits because I could not figure out which parts should go where, how they fit together, etc.   -- but you know this, and should do the move. I suggest putting things into the `opencog/eva/open-psi` directory here: https://github.com/opencog/opencog/tree/master/opencog/eva

**Comment by linas** [comment]
to be clear: the ROS motors, cameras, and microphones need to stay here.  Anything that is not sensory moves to the opencog/eva directory.

**Comment by linas** [comment]
Actually, this file has already been moved: it is here: https://github.com/opencog/opencog/blob/master/opencog/eva/src/psi-dynamics.scm

You should redo your pull request, and put it there, not here.  I want to remove this file, here, to avoid this confusion.

**Comment by eddiemonroe** [comment]
update made to file in opencog repo: https://github.com/opencog/opencog/pull/2789

**Pull request merged**
